### ISSUE TITLE
reflect.Value.SetUint using value obtained using unexported field

### ISSUE THREAD

**Issue by pwaller** [remyoudompheng/go-netlink#2]
Hi, nice package!

I'm messing around with this package and I cannot get it to work, unfortunately. If I run `cmd/taskstats` as is, I always get:

```
$ sudo ./taskstats
ErrorMsg = {
  "Header": {
    "Len": 48,
    "Type": 2,
    "Flags": 0,
    "Seq": 0,
    "Pid": 22054
  },
  "Errno": -95,
  "WrongHeader": {
    "Len": 28,
    "Type": 23,
    "Flags": 1,
    "Seq": 0,
    "Pid": 22054
  }
}
operation not supported

```

And if I modify `MakeCmdMessage` to use `TASKSTATS_CMD_ATTR_REGISTER_CPUMASK`:

``` go
func MakeCmdMessage() (msg netlink.GenericNetlinkMessage) {
    msg.Header.Type = 25
    msg.Header.Flags = syscall.NLM_F_REQUEST
    msg.GenHeader.Command = genl.TASKSTATS_CMD_GET
    msg.GenHeader.Version = genl.TASKSTATS_GENL_VERSION
    buf := bytes.NewBuffer([]byte{})
    netlink.PutAttribute(buf, genl.TASKSTATS_CMD_ATTR_REGISTER_CPUMASK, "0-7")
    msg.Data = buf.Bytes()
    return msg
}
```

Then I get this when it tries to write the fields of the taskstats:

```
panic: reflect: reflect.Value.SetUint using value obtained using unexported field

goroutine 16 [running]:
runtime.panic(0x4e1020, 0xc208000ec0)
    /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
reflect.flag.mustBeAssignable(0x97)
    /usr/local/go/src/pkg/reflect/value.go:331 +0x124
reflect.Value.SetUint(0x4e0aa0, 0xc208022020, 0x0, 0x97, 0x8)
    /usr/local/go/src/pkg/reflect/value.go:1660 +0x27
encoding/binary.(*decoder).value(0xc2080204b0, 0x4e0aa0, 0xc208022020, 0x0, 0x97)
    /usr/local/go/src/pkg/encoding/binary/binary.go:500 +0x31a
encoding/binary.(*decoder).value(0xc2080204b0, 0x528060, 0xc208022020, 0x0, 0x196)
    /usr/local/go/src/pkg/encoding/binary/binary.go:476 +0xac5
encoding/binary.Read(0x7f76e0231560, 0xc208028070, 0x7f76e02314b8, 0x0, 0x4d5800, 0xc208022020, 0x0, 0x0)
    /usr/local/go/src/pkg/encoding/binary/binary.go:219 +0x13e5
github.com/remyoudompheng/go-netlink.readAttribute(0xc208028070, 0x4d57a0, 0xc208022000, 0x0, 0x0)
    /home/pwaller/.local/src/github.com/remyoudompheng/go-netlink/attributes.go:88 +0x57a
github.com/remyoudompheng/go-netlink.ReadManyAttributes(0xc208028070, 0x4d57a0, 0xc208022000, 0x0, 0x0)
    /home/pwaller/.local/src/github.com/remyoudompheng/go-netlink/attributes.go:130 +0x4d
github.com/remyoudompheng/go-netlink/genl.ParseGenlTaskstatsMsg(0x190000016c, 0xf, 0xc208062000, 0x15c, 0x15c, 0x0, 0x0, 0x0, 0x0)
    /home/pwaller/.local/src/github.com/remyoudompheng/go-netlink/genl/taskstats.go:36 +0x2e9
main.TestTaskStats(0xc2080203c0)
    /home/pwaller/.local/src/github.com/remyoudompheng/go-netlink/cmd/taskstats/task.go:30 +0x109
main.main()
    /home/pwaller/.local/src/github.com/remyoudompheng/go-netlink/cmd/taskstats/task.go:47 +0x4a
```

Any ideas how to work around this issue?

**Comment by pwaller** [comment]
I think the `operation not supported` error is due to the `msg.Header.Type = 23` - if I change it to `msg.Header.Type = 25` then instead I get the reflection panic.

**Comment by pwaller** [comment]
Hi @remyoudompheng, since I didn't hear from you I'm closing this. Unfortunately it was very hard to use go-netlink in the end because of this, so it would be great if you can suggest anything. But in the end I need this less now than I did in the past.
